layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
      - zackhill.dev

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: zackary.t.hill
  # keybase: your_username
  linkedin: zahill
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Rust
    web_url: https://www.rust-lang.org/
    image_url: https://www.rust-lang.org/static/images/rust-logo-blk.svg

  - name: Python
    web_url: https://www.python.org/
    image_url: /assets/python.png
  
  - name: Unity
    web_url: https://unity.com/
    image_url: /assets/unity.png